name: Integration Steps

on:
  workflow_call:

jobs:
  integrate:
    runs-on: macos-latest
    env:
      KEYSTORE_FILENAME: keystore-release.jks

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java distribution
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add permissions for Gradle
        run: chmod +x gradlew

      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ENCODED_KEYSTORE }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > $KEYSTORE_FILENAME

      - name: Retrieve keystore properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        #keystoreFile path relative to build.gradle.kts file
        run: |
          echo "keystorePath=./../$KEYSTORE_FILENAME" > ./keystore.properties 
          echo "keystorePassword=$KEYSTORE_PASSWORD" >> ./keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> ./keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> ./keystore.properties

      - name: Assemble
        id: 'assemble'
        run: |
          if [ ${{ github.ref_name }} != "release/*" ]; then
            ./gradlew assembleDebug
          else
            ./gradlew assembleRelease
          fi

      - name: Unit Tests
        id: unit_tests
        run: |
          if [ ${{ github.ref_name }} != "release/*" ]; then
            ./gradlew testDebugUnitTest
          else
            ./gradlew testReleaseUnitTest
          fi
        continue-on-error: true

      - name: Instrumented Tests
        id: instrumented_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          # doesn't work in multiline due to parsing issues
          script: if [[ ${{ github.ref_name }} != "release/*" ]]; then ./gradlew connectedDebugAndroidTest; else ./gradlew connectedReleaseAndroidTest; fi
        continue-on-error: true

      - name: Test Results Upload
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/**/TEST-*.xml

      - name: Test Results Presentation
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          files: app/build/**/TEST-*.xml

      - name: Check for failures
        if: steps.unit_tests.outcome == 'failure' || steps.instrumented_tests.outcome == 'failure'
        run: exit 1